//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderClient.OrderEntityEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Catalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item_Catalog()
        {
            this.Item_Unique_Desc = new HashSet<Item_Unique_Desc>();
            this.Items = new HashSet<Item>();
        }
    
        public int id { get; set; }
        public string Item_DCode { get; set; }
        public string Item_Name { get; set; }
        public int InStock { get; set; }
        public int CategoryId { get; set; }
        public string Item_Desc { get; set; }
    
        public virtual Product_Category Product_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Unique_Desc> Item_Unique_Desc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
    }
}
