//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderClient.OrderEntityEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int id { get; set; }
        public string OrderId { get; set; }
        public string ItemName { get; set; }
        public string Item_DCode { get; set; }
        public int RentAmt { get; set; }
        public int Quantity { get; set; }
        public int TotalRent { get; set; }
        public int SecurityDeposit { get; set; }
        public int Tenure { get; set; }
        public string DealerName { get; set; }
    
        public virtual Item_Catalog Item_Catalog { get; set; }
        public virtual User User { get; set; }
    }
}
