//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderClient.OrderEntityEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Unique_Desc
    {
        public int Id { get; set; }
        public string Item_UCode { get; set; }
        public string Item_DCode { get; set; }
        public decimal Cost { get; set; }
        public decimal Cost_Recovered { get; set; }
        public int RentedOut { get; set; }
        public System.DateTime Buy_date { get; set; }
    
        public virtual Item_Catalog Item_Catalog { get; set; }
    }
}
